services:
  - type: web
    name: wedding-frontend
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run serve
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
